ecommerce/blog/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from . import views


app_name = 'blog'



urlpatterns = [
    re_path(r'^post-list/$',views.PostList,name ='postlist'),
    re_path(r'^post-list/(?P<id>\d+)/$',views.PostDetail,name="postdetail"),
    path ('post-create',views.CreatPost, name='post-create'),
    re_path (r'^post-list/update/(?P<id>\d+)/$',views.PostUpdateis,name='update-post'),
    # re_path(r'^(?P<slug_post>[-\w])+/$',views.PostDetail,name="postdetail"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views




if settings.DEBUG:
    urlpatterns = [
    path ('',views.home,name="home"),
    path('admin/', admin.site.urls),
    path ('accounts/',include('accounts.urls',namespace="accounts")),
    path ('blog/',include('blog.urls',namespace='blog')),
    path ('cart/',include('cart.urls',namespace='cart')),
    path ('polls/',include('polls.urls',namespace='polls')),
    path ('products/',include('products.urls',namespace='products')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
                  ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/products/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

from . import views
app_name="products"




urlpatterns = [
    path('productlist',views.ProductListView,name='productlist'),
    re_path(r'^(?P<id>\d+)/$',views.ProductDetailView,name="product_detail_view"),
    path('categorylist', views.CategoryListview, name='categorylistview'),
    re_path(r'^category/(?P<id>\d+)/$',views.CategoryDetail,name= "category_detail")

]

ecommerce/products/models.py
from django.db import models

# Create your models here.

class Brand(models.Model):
    title = models.CharField(unique=True,max_length=100)
    slug = models.SlugField()

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(unique=True,max_length=100)
    description = models.TextField(max_length=500)
    slug =models.SlugField()

    def __str__(self):
        return self.title


class Varations(models.Model):
    title = models.CharField(max_length=120)
    slug= models.SlugField()
    active = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=15,decimal_places=2)
    sale_price = models.DecimalField(max_digits=15,decimal_places=2)
    product = models.ForeignKey('Product',on_delete=models.CASCADE)


    def __str__(self):
        return self.title

    class Meta:
        ordering =["-title"]


    def get_price(self):
        if self.sale_price is not None:
            return self.sale_price
        else :
            return self.price

# class ProductQueryset(models.QuerySet):
#
#     def get_related_product(self, instance):
#         return self.filter(category__in = instance)
#
#
# class ProductManger(models.manager):
#
#     def get_queryset(self):
#         return ProductQueryset(self.model,using=self._db)


class Product(models.Model):
    title = models.CharField(max_length=120,help_text="Enter uniqe title")
    hits = models.IntegerField(default=0)
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    description = models.TextField(max_length=1500,help_text='descrip your Product')
    category = models.ManyToManyField(Category)
    active = models.BooleanField(default=True)
    price = models.DecimalField(decimal_places=2,max_digits=15,help_text="قیمت ها به تومان می باشد.")


    def __str__(self):
        return self.title


    class Meta :
        ordering = ["-title"]




class ProductImage(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    image = models.ImageField()


    def __str__(self):
        return self.product.title



class ProductFeautre(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    hits = models.IntegerField(default=0)
    image = models.ImageField()
    title = models.CharField(max_length=120)
    text = models.TextField(max_length=15000)
    text_right = models.BooleanField(default=False)
    text_css_color = models.CharField(max_length=6, null=True, blank=True)
    show_price = models.BooleanField(default=False)
    make_image_background = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.product.title

ecommerce/products/views.py
from django.db.models import Q
from django.shortcuts import render,get_object_or_404
from .models import Product,Category

# Create your views here.


# .......productLIst...........
def ProductListView(request):
    ProductList= Product.objects.all()
    context = {
        "ProductList":ProductList
    }
    template_name = "productlist.html"

    return render(request,template_name,context)


    # def get_querset(self,*args,**kwargs):
    #     qs = super(ProductListView,self).get_queryset(*args,**kwargs)
    #     query = self.request.POST.get('q')
    #     if query:



def ProductDetailView(request,id):
    product = get_object_or_404(Product,id=id)
    product.hits +=1
    product.save()
    # relatedProduct =Product.objects.filter(category__in=Product.objects.all)
    context = {
        "product":product,
        # 'relatedProduct': relatedProduct
    }
    template_name = "productdetail.html"
    return render(request,template_name,context)


def CategoryListview(request):
    CategoryList = Category.objects.all
    context = {
        "CategoryList":CategoryList
    }
    template_name = "categorylistview.html"
    return render(request,template_name,context)


def CategoryDetail(request,id):
    category = get_object_or_404(Category,id=id)
    product = Product.objects.filter(category=category)
    context = {
        "category":category,
        "product":product
    }
    template_name = "category-detail.html"
    return render(request,template_name,context)

ecommerce/products/templates/category-detail.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <hr>
            <h1>{{ category }}</h1>
            {% for pro in product %}
            <ul>
                <li>title :<a href="{% url 'products:product_detail_view' id=pro.id %}">{{ pro.title }}</a> </li>
                <li>id :{{ pro.id }}</li>
            </ul>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}

ecommerce/products/templates/categorylistview.html
{% extends "base.html" %}
{% block content %}
<hr>
<div class="container">
    <div class="row">
<hr   />
            {% for cat in CategoryList %}
        <div class="col-md-4">
            <div class="card border-success mb-3" style="max-width: 18rem;">
  <div class="card-header bg-transparent border-success"><h4>Category_title :</h4><a href="{% url 'products:category_detail' id=cat.id %}">{{ cat.title }}</a></div>
  <div class="card-body text-success">
    <h5 class="card-title">Success card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
                <div class="card-footer bg-transparent border-success"><h6>Category_id :</h6><small>{{ cat.id }}</small></div>
</div>
        </div>
             {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

ecommerce/products/templates/productdetail.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <hr>
            <ul>
                <li>title :{{ product.title }}</li>
                <li>id :{{ product.id }}</li>
                <li>brand :{{ product.brand.title }}</li>
                {% for cate in product.category.all %}
                <li>category :{{ cate.title}}</li>
                {% endfor %}
            </ul>
            {% if product.productimage_set.count > 0 %}
            {% for img in product.productimage_set.all %}
            <img src="{{ img.image.url}}" alt="Wire" style="width:300px;hight:300px;">

            {% endfor %}

            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

ecommerce/products/templates/productlist.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <hr>
                <h3>Categories</h3>
            {{ ProductList }}
            {% if ProductList.category_set.count >= 1 %}
                {% for cat in ProductList.category_set.all %}
                {{ cat.title }}
                {{ cat.id }}
                {% endfor %}
            {% endif %}
            {% for product in ProductList %}
            <div class="col-md-3">
            <h2>Title : {{ product.title}}</h2>
            <h2>Brand : {{ product.brand.title}}</h2>
            <h2>Category : {{ product.category.title}}</h2>
            <h2>Price : {{ product.price}}</h2>
                {% for cate in product.category.all %}
               <h3>Category : {{ cate.title }} </h3>
                {% endfor %}
            <hr>
            </div>
            <a href="{% url 'products:product_detail_view' id=product.id %}" class="btn btn-primary">View More</a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}