ecommerce/blog/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from . import views


app_name = 'blog'



urlpatterns = [
    re_path(r'^post-list/$',views.PostList,name ='postlist'),
    re_path(r'^post-list/(?P<id>\d+)/$',views.PostDetail,name="postdetail"),
    path ('post-create',views.CreatPost, name='post-create'),
    re_path (r'^post-list/update/(?P<id>\d+)/$',views.PostUpdateis,name='update-post'),
    # re_path(r'^(?P<slug_post>[-\w])+/$',views.PostDetail,name="postdetail"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views




if settings.DEBUG:
    urlpatterns = [
    path ('',views.home,name="home"),
    path('admin/', admin.site.urls),
    path ('accounts/',include('accounts.urls',namespace="accounts")),
    path ('blog/',include('blog.urls',namespace='blog')),
    path ('cart/',include('cart.urls',namespace='cart')),
    path ('polls/',include('polls.urls',namespace='polls')),
    path ('products/',include('products.urls',namespace='products')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
                  ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    age = models.IntegerField(default=0)
    phone = models.IntegerField(default=0)
    image = models.ImageField()
    website = models.URLField()



class Post (models.Model):
    Author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=120,unique=True,blank=False,null=False)
    slug = models.SlugField()
    description = models.TextField(max_length=1000)
    timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now=True,auto_now_add=False)


    def __str__(self):
        return self.title

ecommerce/blog/views.py
from django.shortcuts import render,get_object_or_404,reverse,redirect
from .models import Post
from .froms import CreatePostForm, PostEditForm

# Create your views here.




def PostList(request):
    postlist = Post.objects.all()
    context = {
        "postlist":postlist
    }
    template_name = "postlist.html"
    return render(request,template_name,context)




def PostDetail(request,id):
    post = get_object_or_404(Post,id=id)
    context = {
        'post':post
    }
    template_name = "postdetail.html"
    return render(request,template_name,context)


def PostUpdateis(request,id):
    post = get_object_or_404(Post,id=id)
    if request.user != post.Author :
        return redirect("home")
    else :
        if request.method == "POST" :
            form = PostEditForm(request.POST ,instance=post)
            if form.is_valid():
                form.save()
                return redirect("home")
        else:
            form = PostEditForm(instance=post)
    return render(request,"update-post.html",context={"form":form})

def CreatPost(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST or None)
        if form.is_valid():
            new_post= form.save(commit=False)
            new_post.Author = request.user
            new_post.save()
            return redirect("home")
    else:
        form = CreatePostForm()
    context = {"form":form }
    template_name="CreatePostForm.html"
    return render(request,template_name,context)

ecommerce/blog/templates/CreatePostForm.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <hr  />
            <form method="POST" action="">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.error }}
                    {{ field.label_tag }}
                    {{ field}}
                </div>
                {% endfor %}
                <input type="submit" class="btn btn-primary" value="submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}

ecommerce/blog/templates/postdetail.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <hr>
            <h1>{{ post.title }}</h1><small> <li>{{ post.timestamp }}</li></small>
            <ul>
                <li>{{ post.description }}</li>
                <h6>{{ post.Author }}</li></h6><li>
            </ul>
            {% if request.user == post.Author %}
            <a href="{% url 'blog:update-post' id=post.id %}" class="btn btn-primary">Edit Post</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

ecommerce/blog/templates/postlist.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
            {% for item in postlist %}
        <div class="col-md-3">
            <ul>
                <li><h3>Title:</h3> {{ item.title }} <smal>{{ item.timestamp }}</smal></li>
                <li><h3>description:</h3>{{ item.description }}</li>
                <li><h3>Updated:</h3>{{ item.updated }}</li>
                <li><h>Author: {{ item.Author }}</h></li>
                {{ item.id }}
            </ul>
            <a href="{% url 'blog:postdetail' id=item.id %}" class="btn btn-primary" >View More </a>
        <hr>
                    </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

ecommerce/blog/templates/update-post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.error }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
             <input type="submit" class="btn btn-primary" value="Edit">
            </form>
        </div>
    </div>
</div>
{% endblock %}