ecommerce/accounts/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from . import views




app_name = 'accounts'



urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',views.user_login,name= "login"),
    path('logout/',views.user_logout,name='logout'),
    path ('register/',views.register_user,name='register_user'),
    path('change-password/',views.Change_Password,name="change_password"),
    # re_path(r'(?P<username>[\w,@+-]+)/$',views.ViewProfile,name='viewprofile-with username'),
    # path('profile/',views.ViewProfile,name='viewprofile'),
    path('contact/',views.ContactUs,name='contact')

]

ecommerce/blog/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from . import views


app_name = 'blog'



urlpatterns = [
    re_path(r'^post-list/$',views.PostList,name ='postlist'),
    re_path(r'^post-list/(?P<id>\d+)/$',views.PostDetail,name="postdetail"),
    path ('post-create',views.CreatPost, name='post-create'),
    re_path (r'^post-list/update/(?P<id>\d+)/$',views.PostUpdateis,name='update-post'),
    # re_path(r'^(?P<slug_post>[-\w])+/$',views.PostDetail,name="postdetail"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views




if settings.DEBUG:
    urlpatterns = [
    path ('',views.home,name="home"),
    path('admin/', admin.site.urls),
    path ('accounts/',include('accounts.urls',namespace="accounts")),
    path ('blog/',include('blog.urls',namespace='blog')),
    path ('cart/',include('cart.urls',namespace='cart')),
    path ('polls/',include('polls.urls',namespace='polls')),
    path ('products/',include('products.urls',namespace='products')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
                  ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/products/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

from . import views
app_name="products"




urlpatterns = [
    path('productlist',views.ProductListView,name='productlist'),
    re_path(r'^(?P<id>\d+)/$',views.ProductDetailView,name="product_detail_view"),
    path('categorylist', views.CategoryListview, name='categorylistview'),
    re_path(r'^category/(?P<id>\d+)/$',views.CategoryDetail,name= "category_detail")

]

ecommerce/templates/base.html
<!doctype html>
<body lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <title>{% block title %} ecommerc shop  {% endblock  %}</title>
  </head>
<body>
{% include "navbar.html" %}
{% block content %}
{% endblock %}
<!--..........................start web ...................-->
<p><hr></p>
      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo,
                tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada
                magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus
                commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem
                malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id
                ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum
                nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
        </div>
        <hr>
      </div> <!-- /container -->
    <footer class="container">
      <p>&copy; Company 2017-2018</p>
    </footer>
</body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
  </body>
</html>

ecommerce/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="containers">
    <div class="rows">
        <div class="col">
            <h3>
                New begin!! {{ time|date }}
            </h3>
        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/navbar.html
<div class="container">
<!--...........load static file..............-->
 {% load static %}
<!--...........................................-->
<link rel="stylesheet" type="text/css" href="{% static 'css/homestyle.css' %}">
<!-- .........start navbar...........-->
       <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Fixed navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
<!--...................navbar item home ........................-->
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">خانه <span class="sr-only">(current)</span></a>
          </li>
<!--....... time tag............-->
    <li class="nav-item">
      <a class="nav-link">{{ time_now | date:'Y-m-d H:i' }} :تاریخ </a>
    </li>
<!--............. contact item..........-->
          <li class="nav-item">
            <a class="nav-link disabled" href="{% url 'accounts:contact' %}">تماس ما </a>
          </li>

<!--.............user tag............-->

    <li class="nav-item">
      <a class="nav-link">{{request.user }}</a>
    </li>

<!--.............. drop down  product.................-->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown04" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">محصولات</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'products:productlist' %}">لیست محصولات</a>
              <a class="dropdown-item" href="{% url 'products:categorylistview' %}">دسته بندی محصولات </a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>

<!--.............. drop down blog..................-->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">بلاگ</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'blog:postlist' %}">لیست</a>
              <a class="dropdown-item" href="{% url 'blog:post-create' %}">انتشار پست</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>

              {% if request.user.is_authenticated %}

<!--................. drop Down .login ...................-->

            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown02" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">{{ request.user }}</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'home' %}">خانه</a>
              <a class="dropdown-item" href="#">Edit Profile</a>
              <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password</a>
            </div>

<!--............item login..................-->
          <li class="nav-item">
            <a class="nav-link " href="{% url 'accounts:logout' %}">log out </a>
          </li>

                {% else %}
<!--......... Drop down guest.................-->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown03" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">مهمان</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'accounts:register_user' %}">ثبت نام</a>
              <a class="dropdown-item" href="#">Rest password</a>
              <a class="dropdown-item" href="{% url 'accounts:login' %}">ورود</a>
            </div>
            </li>
                {% endif %}


 <!--..................search tag.............-->
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

<!--.....................jumbotron..................-->
      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Mohammad Shir Mohammadi!</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout
            called a jumbotron and three supporting pieces of content. Use it as a starting point to create something
            more unique.</p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
      </div>

<!--.........close container............-->
</div>